[build]
  command = "nuxt generate"
  publish = "dist"

[[headers]]
  for = "/*.js"
    [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.html"
    [headers.values]
    Content-Type = "text/html"
